language: python

python:
  - "2.7"
  - "2.6"
  - "3.3"
  - "3.4"

install:
  - pip install -r requirements.txt -r requirements-testing.txt
  - pip install coveralls

script: py.test

after_success: coveralls
