[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sphinx-autobuild"
readme = "README.md"
authors = [
  {name = "Jonathan Stoppani", email = "jonathan@stoppani.name"},
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
home-page = "https://github.com/executablebooks/sphinx-autobuild"
license = "MIT"
requires-python = ">=3.7"
dependencies = [
  "sphinx",
  "livereload",
  "colorama",
]

[project.scripts]
sphinx-autobuild = "sphinx_autobuild.__main__:main"

[project.optional-dependencies]
test = ["pytest", "pytest-cov"]
docs = []

[tool.coverage.run]
branch = true
omit = [
  "*/conftest.py",
  "docs/*",
]

[tool.coverage.report]
exclude_lines = [
  "pragma: no cover",
  "NOCOV",
  "if __name__ == .__main__.:"
]

[tool.coverage.html]
directory = ".htmlcov"

